# This file will have the fucntions to proivde basic maths operations
def add(a, b):
    return a + b

def sub(a, b):
    return a - b

def mul(a, b):
    return a * b

def div(a, b):
    return a / b    

def mod(a, b):
    return a % b

def pow(a, b):
    return a ** b

def floordiv(a, b):
    return a // b

def isEven(a):
    return a % 2 == 0   

def isOdd(a):
    return a % 2 != 0

def isPrime(a):
    for i in range(2, a):
        if a % i == 0:
            return False
    return True

def factorial(a):
    fact = 1
    for i in range(1, a+1):
        fact = fact * i
    return fact

# This function is to find the next number in a series
# E.g.
# a => is a list
# when a is [1, 2, 3, 4, 5] then the return is 6
# when a is [1, 3, 5, 7, 9] then the return is 11
# when a is [2, 4, 8, 16] then the return is 32
# when a is [2, 3, 5, 7] then the return is 11
# when a is [0, 5, 10, 15] then the return is 20
def nextNumber(a):
    diff = a[1] - a[0]
    for i in range(1, len(a)):
        if a[i] - a[i-1] != diff:
            return "Invalid"
    return a[-1] + diff
# Note: this autogenerated function is not fully correct. It is just to see what CoPilot will suggest according to the comments above

def main():
    a = 10
    b = 20
    print("Addition of {} and {} is: {}".format(a, b, add(a, b)))
    print("Subtraction of {} and {} is: {}".format(a, b, sub(a, b)))
    print("Multiplication of {} and {} is: {}".format(a, b, mul(a, b)))
    print("Division of {} and {} is: {}".format(a, b, div(a, b)))
    print("Modulus of {} and {} is: {}".format(a, b, mod(a, b)))
    print("Power of {} and {} is: {}".format(a, b, pow(a, b)))
    print("Floor Division of {} and {} is: {}".format(a, b, floordiv(a, b)))